/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorMovie implements java.io.Serializable {

	private static final long serialVersionUID = -1429438532;

	private final java.lang.Integer id;
	private final java.lang.Integer movieId;
	private final java.lang.Integer actorId;
	private final java.lang.String  role;
	private final java.lang.Byte    mainRole;

	public ActorMovie(
		java.lang.Integer id,
		java.lang.Integer movieId,
		java.lang.Integer actorId,
		java.lang.String  role,
		java.lang.Byte    mainRole
	) {
		this.id = id;
		this.movieId = movieId;
		this.actorId = actorId;
		this.role = role;
		this.mainRole = mainRole;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.Integer getMovieId() {
		return this.movieId;
	}

	public java.lang.Integer getActorId() {
		return this.actorId;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public java.lang.Byte getMainRole() {
		return this.mainRole;
	}
}
