/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Director implements java.io.Serializable {

	private static final long serialVersionUID = -1704893921;

	private final java.lang.Integer id;
	private final java.lang.String  name;
	private final java.lang.String  surname;
	private final java.lang.Long    jmdbid;

	public Director(
		java.lang.Integer id,
		java.lang.String  name,
		java.lang.String  surname,
		java.lang.Long    jmdbid
	) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.jmdbid = jmdbid;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public java.lang.Long getJmdbid() {
		return this.jmdbid;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}

		Director director = (Director) o;

		if (jmdbid != null ? !jmdbid.equals(director.jmdbid) : director.jmdbid != null) {
			return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		return jmdbid != null ? jmdbid.hashCode() : 0;
	}
}
