/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenreMovie implements java.io.Serializable {

	private static final long serialVersionUID = -725069309;

	private final java.lang.Integer id;
	private final java.lang.Integer movieId;
	private final java.lang.Integer genreId;

	public GenreMovie(
		java.lang.Integer id,
		java.lang.Integer movieId,
		java.lang.Integer genreId
	) {
		this.id = id;
		this.movieId = movieId;
		this.genreId = genreId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.Integer getMovieId() {
		return this.movieId;
	}

	public java.lang.Integer getGenreId() {
		return this.genreId;
	}
}
