/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movie implements java.io.Serializable {

	private static final long serialVersionUID = -1837507459;

	private final java.lang.Integer id;
	private final java.lang.String  title;
	private final java.lang.String  language;
	private final java.sql.Date     releaseDate;
	private final java.lang.Long    budget;
	private final java.lang.Long    revenue;
	private final java.lang.Double  popularity;
	private final java.lang.Integer voteCount;
	private final java.lang.Double  voteAverage;
	private final java.lang.Integer genreId;
	private java.lang.Long jmdbid;

	public Movie(
		java.lang.Integer id,
		java.lang.String  title,
		java.lang.String  language,
		java.sql.Date     releaseDate,
		java.lang.Long    budget,
		java.lang.Long    revenue,
		java.lang.Double  popularity,
		java.lang.Integer voteCount,
		java.lang.Double  voteAverage,
		java.lang.Integer genreId,
		java.lang.Long    jmdbid
	) {
		this.id = id;
		this.title = title;
		this.language = language;
		this.releaseDate = releaseDate;
		this.budget = budget;
		this.revenue = revenue;
		this.popularity = popularity;
		this.voteCount = voteCount;
		this.voteAverage = voteAverage;
		this.genreId = genreId;
		this.jmdbid = jmdbid;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public java.sql.Date getReleaseDate() {
		return this.releaseDate;
	}

	public java.lang.Long getBudget() {
		return this.budget;
	}

	public java.lang.Long getRevenue() {
		return this.revenue;
	}

	public java.lang.Double getPopularity() {
		return this.popularity;
	}

	public java.lang.Integer getVoteCount() {
		return this.voteCount;
	}

	public java.lang.Double getVoteAverage() {
		return this.voteAverage;
	}

	public java.lang.Integer getGenreId() {
		return this.genreId;
	}

	public java.lang.Long getJmdbid() {
		return this.jmdbid;
	}

	public void setJmdbid(Long jmdbid) {
		this.jmdbid = jmdbid;
	}
}
