/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorMovieRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = -1769592116;

	/**
	 * Setter for <code>films.Actor_Movie.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>films.Actor_Movie.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>films.Actor_Movie.movie_id</code>.
	 */
	public void setMovieId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>films.Actor_Movie.movie_id</code>.
	 */
	public java.lang.Integer getMovieId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>films.Actor_Movie.actor_id</code>.
	 */
	public void setActorId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>films.Actor_Movie.actor_id</code>.
	 */
	public java.lang.Integer getActorId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>films.Actor_Movie.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>films.Actor_Movie.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>films.Actor_Movie.main_role</code>.
	 */
	public void setMainRole(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>films.Actor_Movie.main_role</code>.
	 */
	public java.lang.Byte getMainRole() {
		return (java.lang.Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE.MOVIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE.ACTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE.MAIN_ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMovieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getActorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getMainRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord value2(java.lang.Integer value) {
		setMovieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord value3(java.lang.Integer value) {
		setActorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord value4(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord value5(java.lang.Byte value) {
		setMainRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorMovieRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.Byte value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActorMovieRecord
	 */
	public ActorMovieRecord() {
		super(pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE);
	}

	/**
	 * Create a detached, initialised ActorMovieRecord
	 */
	public ActorMovieRecord(java.lang.Integer id, java.lang.Integer movieId, java.lang.Integer actorId, java.lang.String role, java.lang.Byte mainRole) {
		super(pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE);

		setValue(0, id);
		setValue(1, movieId);
		setValue(2, actorId);
		setValue(3, role);
		setValue(4, mainRole);
	}
}
