/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 1267089866;

	/**
	 * Setter for <code>films.Actor.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>films.Actor.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>films.Actor.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>films.Actor.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>films.Actor.surname</code>.
	 */
	public void setSurname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>films.Actor.surname</code>.
	 */
	public java.lang.String getSurname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>films.Actor.sex</code>.
	 */
	public void setSex(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>films.Actor.sex</code>.
	 */
	public java.lang.String getSex() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>films.Actor.jmdbid</code>.
	 */
	public void setJmdbid(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>films.Actor.jmdbid</code>.
	 */
	public java.lang.Long getJmdbid() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR.SURNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR.JMDBID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSurname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getJmdbid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord value3(java.lang.String value) {
		setSurname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord value4(java.lang.String value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord value5(java.lang.Long value) {
		setJmdbid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Long value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActorRecord
	 */
	public ActorRecord() {
		super(pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR);
	}

	/**
	 * Create a detached, initialised ActorRecord
	 */
	public ActorRecord(java.lang.Integer id, java.lang.String name, java.lang.String surname, java.lang.String sex, java.lang.Long jmdbid) {
		super(pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR);

		setValue(0, id);
		setValue(1, name);
		setValue(2, surname);
		setValue(3, sex);
		setValue(4, jmdbid);
	}
}
