/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectorRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 1721894628;

	/**
	 * Setter for <code>films.Director.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>films.Director.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>films.Director.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>films.Director.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>films.Director.surname</code>.
	 */
	public void setSurname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>films.Director.surname</code>.
	 */
	public java.lang.String getSurname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>films.Director.jmdbid</code>.
	 */
	public void setJmdbid(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>films.Director.jmdbid</code>.
	 */
	public java.lang.Long getJmdbid() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR.SURNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR.JMDBID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSurname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getJmdbid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorRecord value3(java.lang.String value) {
		setSurname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorRecord value4(java.lang.Long value) {
		setJmdbid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DirectorRecord
	 */
	public DirectorRecord() {
		super(pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR);
	}

	/**
	 * Create a detached, initialised DirectorRecord
	 */
	public DirectorRecord(java.lang.Integer id, java.lang.String name, java.lang.String surname, java.lang.Long jmdbid) {
		super(pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR);

		setValue(0, id);
		setValue(1, name);
		setValue(2, surname);
		setValue(3, jmdbid);
	}
}
