/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectorMovieRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1819365163;

	/**
	 * Setter for <code>films.Director_Movie.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>films.Director_Movie.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>films.Director_Movie.movie_id</code>.
	 */
	public void setMovieId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>films.Director_Movie.movie_id</code>.
	 */
	public java.lang.Integer getMovieId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>films.Director_Movie.director_id</code>.
	 */
	public void setDirectorId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>films.Director_Movie.director_id</code>.
	 */
	public java.lang.Integer getDirectorId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE.MOVIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE.DIRECTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMovieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getDirectorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorMovieRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorMovieRecord value2(java.lang.Integer value) {
		setMovieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorMovieRecord value3(java.lang.Integer value) {
		setDirectorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DirectorMovieRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DirectorMovieRecord
	 */
	public DirectorMovieRecord() {
		super(pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE);
	}

	/**
	 * Create a detached, initialised DirectorMovieRecord
	 */
	public DirectorMovieRecord(java.lang.Integer id, java.lang.Integer movieId, java.lang.Integer directorId) {
		super(pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE);

		setValue(0, id);
		setValue(1, movieId);
		setValue(2, directorId);
	}
}
