/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenreMovieRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 249984028;

	/**
	 * Setter for <code>films.Genre_Movie.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>films.Genre_Movie.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>films.Genre_Movie.movie_id</code>.
	 */
	public void setMovieId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>films.Genre_Movie.movie_id</code>.
	 */
	public java.lang.Integer getMovieId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>films.Genre_Movie.genre_id</code>.
	 */
	public void setGenreId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>films.Genre_Movie.genre_id</code>.
	 */
	public java.lang.Integer getGenreId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE.MOVIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE.GENRE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMovieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getGenreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GenreMovieRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GenreMovieRecord value2(java.lang.Integer value) {
		setMovieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GenreMovieRecord value3(java.lang.Integer value) {
		setGenreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GenreMovieRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GenreMovieRecord
	 */
	public GenreMovieRecord() {
		super(pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE);
	}

	/**
	 * Create a detached, initialised GenreMovieRecord
	 */
	public GenreMovieRecord(java.lang.Integer id, java.lang.Integer movieId, java.lang.Integer genreId) {
		super(pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE);

		setValue(0, id);
		setValue(1, movieId);
		setValue(2, genreId);
	}
}
