/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actor extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> {

	private static final long serialVersionUID = 1676170525;

	/**
	 * The reference instance of <code>films.Actor</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Actor ACTOR = new pl.edu.agh.integracja.films.films.db.tables.Actor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord.class;
	}

	/**
	 * The column <code>films.Actor.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Actor.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>films.Actor.surname</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord, java.lang.String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>films.Actor.sex</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>films.Actor.jmdbid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord, java.lang.Long> JMDBID = createField("jmdbid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>films.Actor</code> table reference
	 */
	public Actor() {
		this("Actor", null);
	}

	/**
	 * Create an aliased <code>films.Actor</code> table reference
	 */
	public Actor(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR);
	}

	private Actor(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Actor(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_ACTOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_ACTOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.Actor as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.Actor(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.Actor rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.Actor(name, null);
	}
}
