/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorMovie extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> {

	private static final long serialVersionUID = 1050106234;

	/**
	 * The reference instance of <code>films.Actor_Movie</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.ActorMovie ACTOR_MOVIE = new pl.edu.agh.integracja.films.films.db.tables.ActorMovie();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord.class;
	}

	/**
	 * The column <code>films.Actor_Movie.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Actor_Movie.movie_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.Integer> MOVIE_ID = createField("movie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Actor_Movie.actor_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.Integer> ACTOR_ID = createField("actor_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Actor_Movie.role</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * The column <code>films.Actor_Movie.main_role</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.Byte> MAIN_ROLE = createField("main_role", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>films.Actor_Movie</code> table reference
	 */
	public ActorMovie() {
		this("Actor_Movie", null);
	}

	/**
	 * Create an aliased <code>films.Actor_Movie</code> table reference
	 */
	public ActorMovie(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE);
	}

	private ActorMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActorMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord, java.lang.Integer> getIdentity() {
		return pl.edu.agh.integracja.films.films.db.Keys.IDENTITY_ACTOR_MOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_ACTOR_MOVIE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.ActorMovieRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_ACTOR_MOVIE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.ActorMovie as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.ActorMovie(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.ActorMovie rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.ActorMovie(name, null);
	}
}
