/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Director extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> {

	private static final long serialVersionUID = -1280140581;

	/**
	 * The reference instance of <code>films.Director</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Director DIRECTOR = new pl.edu.agh.integracja.films.films.db.tables.Director();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord.class;
	}

	/**
	 * The column <code>films.Director.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Director.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>films.Director.surname</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord, java.lang.String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>films.Director.jmdbid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord, java.lang.Long> JMDBID = createField("jmdbid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>films.Director</code> table reference
	 */
	public Director() {
		this("Director", null);
	}

	/**
	 * Create an aliased <code>films.Director</code> table reference
	 */
	public Director(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR);
	}

	private Director(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Director(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord, java.lang.Integer> getIdentity() {
		return pl.edu.agh.integracja.films.films.db.Keys.IDENTITY_DIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_DIRECTOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_DIRECTOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.Director as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.Director(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.Director rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.Director(name, null);
	}
}
