/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectorMovie extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> {

	private static final long serialVersionUID = 132754530;

	/**
	 * The reference instance of <code>films.Director_Movie</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.DirectorMovie DIRECTOR_MOVIE = new pl.edu.agh.integracja.films.films.db.tables.DirectorMovie();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord.class;
	}

	/**
	 * The column <code>films.Director_Movie.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Director_Movie.movie_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord, java.lang.Integer> MOVIE_ID = createField("movie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Director_Movie.director_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord, java.lang.Integer> DIRECTOR_ID = createField("director_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>films.Director_Movie</code> table reference
	 */
	public DirectorMovie() {
		this("Director_Movie", null);
	}

	/**
	 * Create an aliased <code>films.Director_Movie</code> table reference
	 */
	public DirectorMovie(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE);
	}

	private DirectorMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> aliased) {
		this(alias, aliased, null);
	}

	private DirectorMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord, java.lang.Integer> getIdentity() {
		return pl.edu.agh.integracja.films.films.db.Keys.IDENTITY_DIRECTOR_MOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_DIRECTOR_MOVIE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.DirectorMovieRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_DIRECTOR_MOVIE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.DirectorMovie as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.DirectorMovie(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.DirectorMovie rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.DirectorMovie(name, null);
	}
}
