/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genre extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord> {

	private static final long serialVersionUID = -1036474249;

	/**
	 * The reference instance of <code>films.Genre</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Genre GENRE = new pl.edu.agh.integracja.films.films.db.tables.Genre();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord.class;
	}

	/**
	 * The column <code>films.Genre.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Genre.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * Create a <code>films.Genre</code> table reference
	 */
	public Genre() {
		this("Genre", null);
	}

	/**
	 * Create an aliased <code>films.Genre</code> table reference
	 */
	public Genre(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.Genre.GENRE);
	}

	private Genre(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord> aliased) {
		this(alias, aliased, null);
	}

	private Genre(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_GENRE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_GENRE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.Genre as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.Genre(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.Genre rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.Genre(name, null);
	}
}
