/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenreMovie extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> {

	private static final long serialVersionUID = -1991981435;

	/**
	 * The reference instance of <code>films.Genre_Movie</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.GenreMovie GENRE_MOVIE = new pl.edu.agh.integracja.films.films.db.tables.GenreMovie();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord.class;
	}

	/**
	 * The column <code>films.Genre_Movie.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Genre_Movie.movie_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord, java.lang.Integer> MOVIE_ID = createField("movie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Genre_Movie.genre_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord, java.lang.Integer> GENRE_ID = createField("genre_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>films.Genre_Movie</code> table reference
	 */
	public GenreMovie() {
		this("Genre_Movie", null);
	}

	/**
	 * Create an aliased <code>films.Genre_Movie</code> table reference
	 */
	public GenreMovie(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.GenreMovie.GENRE_MOVIE);
	}

	private GenreMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> aliased) {
		this(alias, aliased, null);
	}

	private GenreMovie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord, java.lang.Integer> getIdentity() {
		return pl.edu.agh.integracja.films.films.db.Keys.IDENTITY_GENRE_MOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_GENRE_MOVIE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.GenreMovieRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_GENRE_MOVIE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.GenreMovie as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.GenreMovie(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.GenreMovie rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.GenreMovie(name, null);
	}
}
