/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movie extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord> {

	private static final long serialVersionUID = -1303745470;

	/**
	 * The reference instance of <code>films.Movie</code>
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Movie MOVIE = new pl.edu.agh.integracja.films.films.db.tables.Movie();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord> getRecordType() {
		return pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord.class;
	}

	/**
	 * The column <code>films.Movie.id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.title</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>films.Movie.language</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>films.Movie.release_date</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.sql.Date> RELEASE_DATE = createField("release_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.budget</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Long> BUDGET = createField("budget", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.revenue</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Long> REVENUE = createField("revenue", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.popularity</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Double> POPULARITY = createField("popularity", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.vote_count</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Integer> VOTE_COUNT = createField("vote_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.vote_average</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Double> VOTE_AVERAGE = createField("vote_average", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.genre_id</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Integer> GENRE_ID = createField("genre_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>films.Movie.jmdbid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Long> JMDBID = createField("jmdbid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>films.Movie</code> table reference
	 */
	public Movie() {
		this("Movie", null);
	}

	/**
	 * Create an aliased <code>films.Movie</code> table reference
	 */
	public Movie(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.films.db.tables.Movie.MOVIE);
	}

	private Movie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movie(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.films.db.Films.FILMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord, java.lang.Integer> getIdentity() {
		return pl.edu.agh.integracja.films.films.db.Keys.IDENTITY_MOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.films.db.Keys.KEY_MOVIE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.films.db.tables.records.MovieRecord>>asList(pl.edu.agh.integracja.films.films.db.Keys.KEY_MOVIE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.films.db.tables.Movie as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.films.db.tables.Movie(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.films.db.tables.Movie rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.films.db.tables.Movie(name, null);
	}
}
