/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> {

	private static final long serialVersionUID = -918405517;

	/**
	 * The reference instance of <code>jmdb.actors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Actors ACTORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Actors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord.class;
	}

	/**
	 * The column <code>jmdb.actors.actorid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord, org.jooq.types.UInteger> ACTORID = createField("actorid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.actors.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * The column <code>jmdb.actors.sex</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex> SEX = createField("sex", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex.class), this, "");

	/**
	 * Create a <code>jmdb.actors</code> table reference
	 */
	public Actors() {
		this("actors", null);
	}

	/**
	 * Create an aliased <code>jmdb.actors</code> table reference
	 */
	public Actors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS);
	}

	private Actors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Actors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord, org.jooq.types.UInteger> getIdentity() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.IDENTITY_ACTORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_ACTORS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_ACTORS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Actors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Actors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Actors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Actors(name, null);
	}
}
