/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Business extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord> {

	private static final long serialVersionUID = 683762074;

	/**
	 * The reference instance of <code>jmdb.business</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Business BUSINESS = new pl.edu.agh.integracja.films.jmdb.db.tables.Business();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord.class;
	}

	/**
	 * The column <code>jmdb.business.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.business.businesstext</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord, java.lang.String> BUSINESSTEXT = createField("businesstext", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * Create a <code>jmdb.business</code> table reference
	 */
	public Business() {
		this("business", null);
	}

	/**
	 * Create an aliased <code>jmdb.business</code> table reference
	 */
	public Business(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Business.BUSINESS);
	}

	private Business(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord> aliased) {
		this(alias, aliased, null);
	}

	private Business(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_BUSINESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.BusinessRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_BUSINESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Business as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Business(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Business rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Business(name, null);
	}
}
