/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Colorinfo extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord> {

	private static final long serialVersionUID = -1841378364;

	/**
	 * The reference instance of <code>jmdb.colorinfo</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo COLORINFO = new pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord.class;
	}

	/**
	 * The column <code>jmdb.colorinfo.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.colorinfo.color</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord, java.lang.String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>jmdb.colorinfo.addition</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord, java.lang.String> ADDITION = createField("addition", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.colorinfo</code> table reference
	 */
	public Colorinfo() {
		this("colorinfo", null);
	}

	/**
	 * Create an aliased <code>jmdb.colorinfo</code> table reference
	 */
	public Colorinfo(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO);
	}

	private Colorinfo(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Colorinfo(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo(name, null);
	}
}
