/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Composers extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord> {

	private static final long serialVersionUID = 347117662;

	/**
	 * The reference instance of <code>jmdb.composers</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Composers COMPOSERS = new pl.edu.agh.integracja.films.jmdb.db.tables.Composers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord.class;
	}

	/**
	 * The column <code>jmdb.composers.composerid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord, org.jooq.types.UInteger> COMPOSERID = createField("composerid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.composers.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.composers</code> table reference
	 */
	public Composers() {
		this("composers", null);
	}

	/**
	 * Create an aliased <code>jmdb.composers</code> table reference
	 */
	public Composers(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Composers.COMPOSERS);
	}

	private Composers(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Composers(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord, org.jooq.types.UInteger> getIdentity() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.IDENTITY_COMPOSERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_COMPOSERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.ComposersRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_COMPOSERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Composers as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Composers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Composers rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Composers(name, null);
	}
}
