/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countries extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord> {

	private static final long serialVersionUID = 1747837011;

	/**
	 * The reference instance of <code>jmdb.countries</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Countries COUNTRIES = new pl.edu.agh.integracja.films.jmdb.db.tables.Countries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord.class;
	}

	/**
	 * The column <code>jmdb.countries.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.countries.country</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.countries</code> table reference
	 */
	public Countries() {
		this("countries", null);
	}

	/**
	 * Create an aliased <code>jmdb.countries</code> table reference
	 */
	public Countries(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Countries.COUNTRIES);
	}

	private Countries(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Countries(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.CountriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Countries as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Countries(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Countries rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Countries(name, null);
	}
}
