/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Directors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord> {

	private static final long serialVersionUID = 914495178;

	/**
	 * The reference instance of <code>jmdb.directors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Directors DIRECTORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Directors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord.class;
	}

	/**
	 * The column <code>jmdb.directors.directorid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord, org.jooq.types.UInteger> DIRECTORID = createField("directorid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.directors.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.directors</code> table reference
	 */
	public Directors() {
		this("directors", null);
	}

	/**
	 * Create an aliased <code>jmdb.directors</code> table reference
	 */
	public Directors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Directors.DIRECTORS);
	}

	private Directors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Directors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord, org.jooq.types.UInteger> getIdentity() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.IDENTITY_DIRECTORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_DIRECTORS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.DirectorsRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_DIRECTORS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Directors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Directors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Directors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Directors(name, null);
	}
}
