/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distributors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord> {

	private static final long serialVersionUID = -1798601355;

	/**
	 * The reference instance of <code>jmdb.distributors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Distributors DISTRIBUTORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Distributors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord.class;
	}

	/**
	 * The column <code>jmdb.distributors.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.distributors.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * The column <code>jmdb.distributors.addition</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord, java.lang.String> ADDITION = createField("addition", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.distributors</code> table reference
	 */
	public Distributors() {
		this("distributors", null);
	}

	/**
	 * Create an aliased <code>jmdb.distributors</code> table reference
	 */
	public Distributors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS);
	}

	private Distributors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Distributors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Distributors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Distributors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Distributors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Distributors(name, null);
	}
}
