/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Editors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord> {

	private static final long serialVersionUID = -55745621;

	/**
	 * The reference instance of <code>jmdb.editors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Editors EDITORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Editors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord.class;
	}

	/**
	 * The column <code>jmdb.editors.editorid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord, org.jooq.types.UInteger> EDITORID = createField("editorid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.editors.name</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.editors</code> table reference
	 */
	public Editors() {
		this("editors", null);
	}

	/**
	 * Create an aliased <code>jmdb.editors</code> table reference
	 */
	public Editors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Editors.EDITORS);
	}

	private Editors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Editors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord, org.jooq.types.UInteger> getIdentity() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.IDENTITY_EDITORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_EDITORS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.EditorsRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_EDITORS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Editors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Editors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Editors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Editors(name, null);
	}
}
