/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genres extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord> {

	private static final long serialVersionUID = 2128816666;

	/**
	 * The reference instance of <code>jmdb.genres</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Genres GENRES = new pl.edu.agh.integracja.films.jmdb.db.tables.Genres();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord.class;
	}

	/**
	 * The column <code>jmdb.genres.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.genres.genre</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord, java.lang.String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.genres</code> table reference
	 */
	public Genres() {
		this("genres", null);
	}

	/**
	 * Create an aliased <code>jmdb.genres</code> table reference
	 */
	public Genres(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Genres.GENRES);
	}

	private Genres(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord> aliased) {
		this(alias, aliased, null);
	}

	private Genres(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.GenresRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Genres as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Genres(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Genres rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Genres(name, null);
	}
}
