/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keywords extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord> {

	private static final long serialVersionUID = -1113272729;

	/**
	 * The reference instance of <code>jmdb.keywords</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Keywords KEYWORDS = new pl.edu.agh.integracja.films.jmdb.db.tables.Keywords();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord.class;
	}

	/**
	 * The column <code>jmdb.keywords.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.keywords.keyword</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord, java.lang.String> KEYWORD = createField("keyword", org.jooq.impl.SQLDataType.VARCHAR.length(125).nullable(false), this, "");

	/**
	 * Create a <code>jmdb.keywords</code> table reference
	 */
	public Keywords() {
		this("keywords", null);
	}

	/**
	 * Create an aliased <code>jmdb.keywords</code> table reference
	 */
	public Keywords(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS);
	}

	private Keywords(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Keywords(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Keywords as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Keywords(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Keywords rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Keywords(name, null);
	}
}
