/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord> {

	private static final long serialVersionUID = 546581211;

	/**
	 * The reference instance of <code>jmdb.language</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Language LANGUAGE = new pl.edu.agh.integracja.films.jmdb.db.tables.Language();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord.class;
	}

	/**
	 * The column <code>jmdb.language.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.language.language</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord, java.lang.String> LANGUAGE_ = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>jmdb.language.addition</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord, java.lang.String> ADDITION = createField("addition", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.language</code> table reference
	 */
	public Language() {
		this("language", null);
	}

	/**
	 * Create an aliased <code>jmdb.language</code> table reference
	 */
	public Language(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Language.LANGUAGE);
	}

	private Language(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Language(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.LanguageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Language as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Language(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Language rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Language(name, null);
	}
}
