/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2cinematgrs extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord> {

	private static final long serialVersionUID = 306546168;

	/**
	 * The reference instance of <code>jmdb.movies2cinematgrs</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs MOVIES2CINEMATGRS = new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord.class;
	}

	/**
	 * The column <code>jmdb.movies2cinematgrs.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2cinematgrs.cinematid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord, org.jooq.types.UInteger> CINEMATID = createField("cinematid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2cinematgrs.addition</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord, java.lang.String> ADDITION = createField("addition", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.movies2cinematgrs</code> table reference
	 */
	public Movies2cinematgrs() {
		this("movies2cinematgrs", null);
	}

	/**
	 * Create an aliased <code>jmdb.movies2cinematgrs</code> table reference
	 */
	public Movies2cinematgrs(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS);
	}

	private Movies2cinematgrs(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movies2cinematgrs(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs(name, null);
	}
}
