/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> {

	private static final long serialVersionUID = 193524288;

	/**
	 * The reference instance of <code>jmdb.movies</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies MOVIES = new pl.edu.agh.integracja.films.jmdb.db.tables.Movies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord.class;
	}

	/**
	 * The column <code>jmdb.movies.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies.title</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies.year</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord, java.lang.String> YEAR = createField("year", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>jmdb.movies.imdbid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord, java.lang.String> IMDBID = createField("imdbid", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * Create a <code>jmdb.movies</code> table reference
	 */
	public Movies() {
		this("movies", null);
	}

	/**
	 * Create an aliased <code>jmdb.movies</code> table reference
	 */
	public Movies(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES);
	}

	private Movies(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movies(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord, org.jooq.types.UInteger> getIdentity() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.IDENTITY_MOVIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> getPrimaryKey() {
		return pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_MOVIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord>>asList(pl.edu.agh.integracja.films.jmdb.db.Keys.KEY_MOVIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies(name, null);
	}
}
