/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2actors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord> {

	private static final long serialVersionUID = 37029819;

	/**
	 * The reference instance of <code>jmdb.movies2actors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors MOVIES2ACTORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord.class;
	}

	/**
	 * The column <code>jmdb.movies2actors.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2actors.actorid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord, org.jooq.types.UInteger> ACTORID = createField("actorid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2actors.as_character</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord, java.lang.String> AS_CHARACTER = createField("as_character", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.movies2actors</code> table reference
	 */
	public Movies2actors() {
		this("movies2actors", null);
	}

	/**
	 * Create an aliased <code>jmdb.movies2actors</code> table reference
	 */
	public Movies2actors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors.MOVIES2ACTORS);
	}

	private Movies2actors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movies2actors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2actorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors(name, null);
	}
}
