/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2directors extends org.jooq.impl.TableImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord> {

	private static final long serialVersionUID = -443804377;

	/**
	 * The reference instance of <code>jmdb.movies2directors</code>
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors MOVIES2DIRECTORS = new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord> getRecordType() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord.class;
	}

	/**
	 * The column <code>jmdb.movies2directors.movieid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord, org.jooq.types.UInteger> MOVIEID = createField("movieid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2directors.directorid</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord, org.jooq.types.UInteger> DIRECTORID = createField("directorid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jmdb.movies2directors.addition</code>.
	 */
	public final org.jooq.TableField<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord, java.lang.String> ADDITION = createField("addition", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>jmdb.movies2directors</code> table reference
	 */
	public Movies2directors() {
		this("movies2directors", null);
	}

	/**
	 * Create an aliased <code>jmdb.movies2directors</code> table reference
	 */
	public Movies2directors(java.lang.String alias) {
		this(alias, pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS);
	}

	private Movies2directors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movies2directors(java.lang.String alias, org.jooq.Table<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, pl.edu.agh.integracja.films.jmdb.db.Jmdb.JMDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors as(java.lang.String alias) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors rename(java.lang.String name) {
		return new pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors(name, null);
	}
}
