/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jmdb extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 687926072;

	/**
	 * The reference instance of <code>jmdb</code>
	 */
	public static final Jmdb JMDB = new Jmdb();

	/**
	 * No further instances allowed
	 */
	private Jmdb() {
		super("jmdb");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Business.BUSINESS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO,
			pl.edu.agh.integracja.films.jmdb.db.tables.Composers.COMPOSERS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Countries.COUNTRIES,
			pl.edu.agh.integracja.films.jmdb.db.tables.Directors.DIRECTORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Editors.EDITORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Genres.GENRES,
			pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Language.LANGUAGE,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movielinks.MOVIELINKS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors.MOVIES2ACTORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS,
			pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS);
	}
}
