/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db;

/**
 * Convenience access to all tables in jmdb
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jmdb.actors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Actors ACTORS = pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS;

	/**
	 * The table jmdb.business
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Business BUSINESS = pl.edu.agh.integracja.films.jmdb.db.tables.Business.BUSINESS;

	/**
	 * The table jmdb.colorinfo
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo COLORINFO = pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO;

	/**
	 * The table jmdb.composers
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Composers COMPOSERS = pl.edu.agh.integracja.films.jmdb.db.tables.Composers.COMPOSERS;

	/**
	 * The table jmdb.countries
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Countries COUNTRIES = pl.edu.agh.integracja.films.jmdb.db.tables.Countries.COUNTRIES;

	/**
	 * The table jmdb.directors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Directors DIRECTORS = pl.edu.agh.integracja.films.jmdb.db.tables.Directors.DIRECTORS;

	/**
	 * The table jmdb.distributors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Distributors DISTRIBUTORS = pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS;

	/**
	 * The table jmdb.editors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Editors EDITORS = pl.edu.agh.integracja.films.jmdb.db.tables.Editors.EDITORS;

	/**
	 * The table jmdb.genres
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Genres GENRES = pl.edu.agh.integracja.films.jmdb.db.tables.Genres.GENRES;

	/**
	 * The table jmdb.keywords
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Keywords KEYWORDS = pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS;

	/**
	 * The table jmdb.language
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Language LANGUAGE = pl.edu.agh.integracja.films.jmdb.db.tables.Language.LANGUAGE;

	/**
	 * The table jmdb.movielinks
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movielinks MOVIELINKS = pl.edu.agh.integracja.films.jmdb.db.tables.Movielinks.MOVIELINKS;

	/**
	 * The table jmdb.movies
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies MOVIES = pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES;

	/**
	 * The table jmdb.movies2actors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors MOVIES2ACTORS = pl.edu.agh.integracja.films.jmdb.db.tables.Movies2actors.MOVIES2ACTORS;

	/**
	 * The table jmdb.movies2cinematgrs
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs MOVIES2CINEMATGRS = pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS;

	/**
	 * The table jmdb.movies2composers
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers MOVIES2COMPOSERS = pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS;

	/**
	 * The table jmdb.movies2directors
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors MOVIES2DIRECTORS = pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS;

	/**
	 * The table jmdb.ratings
	 */
	public static final pl.edu.agh.integracja.films.jmdb.db.tables.Ratings RATINGS = pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS;
}
