/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actors implements java.io.Serializable {

	private static final long serialVersionUID = -78248951;

	private final org.jooq.types.UInteger                             actorid;
	private final java.lang.String                                    name;
	private final pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex sex;

	public Actors(
		org.jooq.types.UInteger                             actorid,
		java.lang.String                                    name,
		pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex sex
	) {
		this.actorid = actorid;
		this.name = name;
		this.sex = sex;
	}

	public org.jooq.types.UInteger getActorid() {
		return this.actorid;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex getSex() {
		return this.sex;
	}
}
