/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Colorinfo implements java.io.Serializable {

	private static final long serialVersionUID = 336256128;

	private final org.jooq.types.UInteger movieid;
	private final java.lang.String        color;
	private final java.lang.String        addition;

	public Colorinfo(
		org.jooq.types.UInteger movieid,
		java.lang.String        color,
		java.lang.String        addition
	) {
		this.movieid = movieid;
		this.color = color;
		this.addition = addition;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public java.lang.String getAddition() {
		return this.addition;
	}
}
