/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countries implements java.io.Serializable {

	private static final long serialVersionUID = -742582465;

	private final org.jooq.types.UInteger movieid;
	private final java.lang.String        country;

	public Countries(
		org.jooq.types.UInteger movieid,
		java.lang.String        country
	) {
		this.movieid = movieid;
		this.country = country;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public java.lang.String getCountry() {
		return this.country;
	}
}
