/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Directors implements java.io.Serializable {

	private static final long serialVersionUID = -831221797;

	private final org.jooq.types.UInteger directorid;
	private final java.lang.String        name;

	public Directors(
		org.jooq.types.UInteger directorid,
		java.lang.String        name
	) {
		this.directorid = directorid;
		this.name = name;
	}

	public org.jooq.types.UInteger getDirectorid() {
		return this.directorid;
	}

	public java.lang.String getName() {
		return this.name;
	}
}
