/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Distributors implements java.io.Serializable {

	private static final long serialVersionUID = 1037532114;

	private final org.jooq.types.UInteger movieid;
	private final java.lang.String        name;
	private final java.lang.String        addition;

	public Distributors(
		org.jooq.types.UInteger movieid,
		java.lang.String        name,
		java.lang.String        addition
	) {
		this.movieid = movieid;
		this.name = name;
		this.addition = addition;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public java.lang.String getAddition() {
		return this.addition;
	}
}
