/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genres implements java.io.Serializable {

	private static final long serialVersionUID = 1046066197;

	private final org.jooq.types.UInteger movieid;
	private final java.lang.String        genre;

	public Genres(
		org.jooq.types.UInteger movieid,
		java.lang.String        genre
	) {
		this.movieid = movieid;
		this.genre = genre;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public java.lang.String getGenre() {
		return this.genre;
	}
}
