/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements java.io.Serializable {

	private static final long serialVersionUID = -2043158838;

	private final org.jooq.types.UInteger movieid;
	private final java.lang.String        language;
	private final java.lang.String        addition;

	public Language(
		org.jooq.types.UInteger movieid,
		java.lang.String        language,
		java.lang.String        addition
	) {
		this.movieid = movieid;
		this.language = language;
		this.addition = addition;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public java.lang.String getAddition() {
		return this.addition;
	}
}
