/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2directors implements java.io.Serializable {

	private static final long serialVersionUID = -284640566;

	private final org.jooq.types.UInteger movieid;
	private final org.jooq.types.UInteger directorid;
	private final java.lang.String        addition;

	public Movies2directors(
		org.jooq.types.UInteger movieid,
		org.jooq.types.UInteger directorid,
		java.lang.String        addition
	) {
		this.movieid = movieid;
		this.directorid = directorid;
		this.addition = addition;
	}

	public org.jooq.types.UInteger getMovieid() {
		return this.movieid;
	}

	public org.jooq.types.UInteger getDirectorid() {
		return this.directorid;
	}

	public java.lang.String getAddition() {
		return this.addition;
	}
}
