/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorsRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.ActorsRecord> implements org.jooq.Record3<org.jooq.types.UInteger, java.lang.String, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex> {

	private static final long serialVersionUID = -1040057599;

	/**
	 * Setter for <code>jmdb.actors.actorid</code>.
	 */
	public void setActorid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.actors.actorid</code>.
	 */
	public org.jooq.types.UInteger getActorid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.actors.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.actors.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.actors.sex</code>.
	 */
	public void setSex(pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.actors.sex</code>.
	 */
	public pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex getSex() {
		return (pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS.ACTORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getActorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex value3() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorsRecord value1(org.jooq.types.UInteger value) {
		setActorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorsRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorsRecord value3(pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorsRecord values(org.jooq.types.UInteger value1, java.lang.String value2, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActorsRecord
	 */
	public ActorsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS);
	}

	/**
	 * Create a detached, initialised ActorsRecord
	 */
	public ActorsRecord(org.jooq.types.UInteger actorid, java.lang.String name, pl.edu.agh.integracja.films.jmdb.db.enums.ActorsSex sex) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Actors.ACTORS);

		setValue(0, actorid);
		setValue(1, name);
		setValue(2, sex);
	}
}
