/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColorinfoRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.ColorinfoRecord> implements org.jooq.Record3<org.jooq.types.UInteger, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 752236795;

	/**
	 * Setter for <code>jmdb.colorinfo.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.colorinfo.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.colorinfo.color</code>.
	 */
	public void setColor(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.colorinfo.color</code>.
	 */
	public java.lang.String getColor() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.colorinfo.addition</code>.
	 */
	public void setAddition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.colorinfo.addition</code>.
	 */
	public java.lang.String getAddition() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO.COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO.ADDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ColorinfoRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ColorinfoRecord value2(java.lang.String value) {
		setColor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ColorinfoRecord value3(java.lang.String value) {
		setAddition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ColorinfoRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ColorinfoRecord
	 */
	public ColorinfoRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO);
	}

	/**
	 * Create a detached, initialised ColorinfoRecord
	 */
	public ColorinfoRecord(org.jooq.types.UInteger movieid, java.lang.String color, java.lang.String addition) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Colorinfo.COLORINFO);

		setValue(0, movieid);
		setValue(1, color);
		setValue(2, addition);
	}
}
