/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistributorsRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.DistributorsRecord> implements org.jooq.Record3<org.jooq.types.UInteger, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -137986417;

	/**
	 * Setter for <code>jmdb.distributors.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.distributors.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.distributors.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.distributors.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.distributors.addition</code>.
	 */
	public void setAddition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.distributors.addition</code>.
	 */
	public java.lang.String getAddition() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS.ADDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributorsRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributorsRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributorsRecord value3(java.lang.String value) {
		setAddition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributorsRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DistributorsRecord
	 */
	public DistributorsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS);
	}

	/**
	 * Create a detached, initialised DistributorsRecord
	 */
	public DistributorsRecord(org.jooq.types.UInteger movieid, java.lang.String name, java.lang.String addition) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Distributors.DISTRIBUTORS);

		setValue(0, movieid);
		setValue(1, name);
		setValue(2, addition);
	}
}
