/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeywordsRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.KeywordsRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = -1091495445;

	/**
	 * Setter for <code>jmdb.keywords.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.keywords.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.keywords.keyword</code>.
	 */
	public void setKeyword(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.keywords.keyword</code>.
	 */
	public java.lang.String getKeyword() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS.KEYWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getKeyword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KeywordsRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KeywordsRecord value2(java.lang.String value) {
		setKeyword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KeywordsRecord values(org.jooq.types.UInteger value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KeywordsRecord
	 */
	public KeywordsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS);
	}

	/**
	 * Create a detached, initialised KeywordsRecord
	 */
	public KeywordsRecord(org.jooq.types.UInteger movieid, java.lang.String keyword) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Keywords.KEYWORDS);

		setValue(0, movieid);
		setValue(1, keyword);
	}
}
