/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoviesRecord extends org.jooq.impl.UpdatableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.MoviesRecord> implements org.jooq.Record4<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 146608776;

	/**
	 * Setter for <code>jmdb.movies.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.movies.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.movies.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.movies.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.movies.year</code>.
	 */
	public void setYear(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.movies.year</code>.
	 */
	public java.lang.String getYear() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>jmdb.movies.imdbid</code>.
	 */
	public void setImdbid(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jmdb.movies.imdbid</code>.
	 */
	public java.lang.String getImdbid() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES.IMDBID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getImdbid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoviesRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoviesRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoviesRecord value3(java.lang.String value) {
		setYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoviesRecord value4(java.lang.String value) {
		setImdbid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoviesRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MoviesRecord
	 */
	public MoviesRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES);
	}

	/**
	 * Create a detached, initialised MoviesRecord
	 */
	public MoviesRecord(org.jooq.types.UInteger movieid, java.lang.String title, java.lang.String year, java.lang.String imdbid) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies.MOVIES);

		setValue(0, movieid);
		setValue(1, title);
		setValue(2, year);
		setValue(3, imdbid);
	}
}
