/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2composersRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2composersRecord> implements org.jooq.Record3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 1252753031;

	/**
	 * Setter for <code>jmdb.movies2composers.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.movies2composers.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.movies2composers.composerid</code>.
	 */
	public void setComposerid(org.jooq.types.UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.movies2composers.composerid</code>.
	 */
	public org.jooq.types.UInteger getComposerid() {
		return (org.jooq.types.UInteger) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.movies2composers.addition</code>.
	 */
	public void setAddition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.movies2composers.addition</code>.
	 */
	public java.lang.String getAddition() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS.COMPOSERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS.ADDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value2() {
		return getComposerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2composersRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2composersRecord value2(org.jooq.types.UInteger value) {
		setComposerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2composersRecord value3(java.lang.String value) {
		setAddition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2composersRecord values(org.jooq.types.UInteger value1, org.jooq.types.UInteger value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Movies2composersRecord
	 */
	public Movies2composersRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS);
	}

	/**
	 * Create a detached, initialised Movies2composersRecord
	 */
	public Movies2composersRecord(org.jooq.types.UInteger movieid, org.jooq.types.UInteger composerid, java.lang.String addition) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2composers.MOVIES2COMPOSERS);

		setValue(0, movieid);
		setValue(1, composerid);
		setValue(2, addition);
	}
}
