/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2directorsRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2directorsRecord> implements org.jooq.Record3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 341053035;

	/**
	 * Setter for <code>jmdb.movies2directors.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.movies2directors.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.movies2directors.directorid</code>.
	 */
	public void setDirectorid(org.jooq.types.UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.movies2directors.directorid</code>.
	 */
	public org.jooq.types.UInteger getDirectorid() {
		return (org.jooq.types.UInteger) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.movies2directors.addition</code>.
	 */
	public void setAddition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.movies2directors.addition</code>.
	 */
	public java.lang.String getAddition() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS.DIRECTORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS.ADDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value2() {
		return getDirectorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2directorsRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2directorsRecord value2(org.jooq.types.UInteger value) {
		setDirectorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2directorsRecord value3(java.lang.String value) {
		setAddition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2directorsRecord values(org.jooq.types.UInteger value1, org.jooq.types.UInteger value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Movies2directorsRecord
	 */
	public Movies2directorsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS);
	}

	/**
	 * Create a detached, initialised Movies2directorsRecord
	 */
	public Movies2directorsRecord(org.jooq.types.UInteger movieid, org.jooq.types.UInteger directorid, java.lang.String addition) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2directors.MOVIES2DIRECTORS);

		setValue(0, movieid);
		setValue(1, directorid);
		setValue(2, addition);
	}
}
