/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movies2cinematgrsRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.Movies2cinematgrsRecord> implements org.jooq.Record3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 343525712;

	/**
	 * Setter for <code>jmdb.movies2cinematgrs.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.movies2cinematgrs.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.movies2cinematgrs.cinematid</code>.
	 */
	public void setCinematid(org.jooq.types.UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.movies2cinematgrs.cinematid</code>.
	 */
	public org.jooq.types.UInteger getCinematid() {
		return (org.jooq.types.UInteger) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.movies2cinematgrs.addition</code>.
	 */
	public void setAddition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.movies2cinematgrs.addition</code>.
	 */
	public java.lang.String getAddition() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS.CINEMATID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS.ADDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value2() {
		return getCinematid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2cinematgrsRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2cinematgrsRecord value2(org.jooq.types.UInteger value) {
		setCinematid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2cinematgrsRecord value3(java.lang.String value) {
		setAddition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Movies2cinematgrsRecord values(org.jooq.types.UInteger value1, org.jooq.types.UInteger value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Movies2cinematgrsRecord
	 */
	public Movies2cinematgrsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS);
	}

	/**
	 * Create a detached, initialised Movies2cinematgrsRecord
	 */
	public Movies2cinematgrsRecord(org.jooq.types.UInteger movieid, org.jooq.types.UInteger cinematid, java.lang.String addition) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Movies2cinematgrs.MOVIES2CINEMATGRS);

		setValue(0, movieid);
		setValue(1, cinematid);
		setValue(2, addition);
	}
}
