/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.jmdb.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingsRecord extends org.jooq.impl.TableRecordImpl<pl.edu.agh.integracja.films.jmdb.db.tables.records.RatingsRecord> implements org.jooq.Record4<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = -2056180162;

	/**
	 * Setter for <code>jmdb.ratings.movieid</code>.
	 */
	public void setMovieid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jmdb.ratings.movieid</code>.
	 */
	public org.jooq.types.UInteger getMovieid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jmdb.ratings.rank</code>.
	 */
	public void setRank(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jmdb.ratings.rank</code>.
	 */
	public java.lang.String getRank() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jmdb.ratings.votes</code>.
	 */
	public void setVotes(org.jooq.types.UInteger value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jmdb.ratings.votes</code>.
	 */
	public org.jooq.types.UInteger getVotes() {
		return (org.jooq.types.UInteger) getValue(2);
	}

	/**
	 * Setter for <code>jmdb.ratings.distribution</code>.
	 */
	public void setDistribution(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jmdb.ratings.distribution</code>.
	 */
	public java.lang.String getDistribution() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS.MOVIEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field3() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS.VOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS.DISTRIBUTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getMovieid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value3() {
		return getVotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDistribution();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingsRecord value1(org.jooq.types.UInteger value) {
		setMovieid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingsRecord value2(java.lang.String value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingsRecord value3(org.jooq.types.UInteger value) {
		setVotes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingsRecord value4(java.lang.String value) {
		setDistribution(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingsRecord values(org.jooq.types.UInteger value1, java.lang.String value2, org.jooq.types.UInteger value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RatingsRecord
	 */
	public RatingsRecord() {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS);
	}

	/**
	 * Create a detached, initialised RatingsRecord
	 */
	public RatingsRecord(org.jooq.types.UInteger movieid, java.lang.String rank, org.jooq.types.UInteger votes, java.lang.String distribution) {
		super(pl.edu.agh.integracja.films.jmdb.db.tables.Ratings.RATINGS);

		setValue(0, movieid);
		setValue(1, rank);
		setValue(2, votes);
		setValue(3, distribution);
	}
}
