/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Films extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -79282652;

	/**
	 * The reference instance of <code>films</code>
	 */
	public static final Films FILMS = new Films();

	/**
	 * No further instances allowed
	 */
	private Films() {
		super("films");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR,
			pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE,
			pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR,
			pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE,
			pl.edu.agh.integracja.films.films.db.tables.Genre.GENRE,
			pl.edu.agh.integracja.films.films.db.tables.Movie.MOVIE);
	}
}
