/**
 * This class is generated by jOOQ
 */
package pl.edu.agh.integracja.films.films.db;

/**
 * Convenience access to all tables in films
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table films.Actor
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Actor ACTOR = pl.edu.agh.integracja.films.films.db.tables.Actor.ACTOR;

	/**
	 * The table films.Actor_Movie
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.ActorMovie ACTOR_MOVIE = pl.edu.agh.integracja.films.films.db.tables.ActorMovie.ACTOR_MOVIE;

	/**
	 * The table films.Director
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Director DIRECTOR = pl.edu.agh.integracja.films.films.db.tables.Director.DIRECTOR;

	/**
	 * The table films.Director_Movie
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.DirectorMovie DIRECTOR_MOVIE = pl.edu.agh.integracja.films.films.db.tables.DirectorMovie.DIRECTOR_MOVIE;

	/**
	 * The table films.Genre
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Genre GENRE = pl.edu.agh.integracja.films.films.db.tables.Genre.GENRE;

	/**
	 * The table films.Movie
	 */
	public static final pl.edu.agh.integracja.films.films.db.tables.Movie MOVIE = pl.edu.agh.integracja.films.films.db.tables.Movie.MOVIE;
}
